[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
pump = "FLFGbCf9hiMZceaEp1P1KNzJJFQLyvQCPriMsBygUP1Y"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --bail -t 1000000 tests/**/*.ts"
test-swap = "yarn run ts-mocha -p ./tsconfig.json --bail -t 1000000 tests/**/*.ts -g Swap Token"
build-with-diff-target = "anchor build && cp $HOME/.cargo/target/sbf-solana-solana/release/pump.so $PWD/target/deploy/pump.so"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
